### ISSUE TITLE
Error while running "npm run serve" on a windows OS

### ISSUE THREAD

**Issue by vitorrgg** [ecomclub/storefront-framework#3]
The error happens in both windows10 CLI and GIT BASH. Here is the log:

$ npm run serve

> @ecomplus/storefront@0.0.1 serve C:\Users\vitor\storefront
> storefront-pack serve

storefront\node_modules\@ecomplus\storefront-framework\src\webpack.config.js:203
            .finally(() => {
                    ^

TypeError: slugs.catch(...).then(...).finally is not a function
    at recursive (C:\Users\vitor\storefront\node_modules\@ecomplus\storefront-framework\src\webpack.config.js:203:21)
    at C:\Users\vitor\storefront\node_modules\recursive-readdir\index.js:88:20
    at FSReqWrap.oncomplete (fs.js:167:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ecomplus/storefront@0.0.1 serve: `storefront-pack serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ecomplus/storefront@0.0.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vitor\AppData\Roaming\npm-cache\_logs\2019-05-09T19_47_32_050Z-debug.log

**Comment by leomp12** [comment]
Doesn't seems to be an error or OS incompatibility of the framework itself.
What version of Node.js are you using? `finally` is not supported on Node.js 8 (I'm not sure if supported on Node.js 9) but it's supported on Node.js 10 (current LTS).
