### ISSUE TITLE
error to deploy storefront with windows

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/storefront-framework#78]
Below is ther error log when npm run serve in windows

  './template/scss/styles.scss\n' +
    'Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\n' +
    'TypeError: $ is not a function\n' +
    '    at Module../node_modules/core-js/modules/es.array.index-of.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:4341:1)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Module.<anonymous> (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:3398:137)\n' +
    '    at Module../node_modules/core-js/internals/regexp-exec.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:3500:30)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Module../node_modules/core-js/modules/es.regexp.exec.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:5109:12)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Module.<anonymous> (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:2031:134)\n' +
    '    at Module../node_modules/core-js/internals/indexed-object.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:2049:30)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Object../node_modules/core-js/internals/to-indexed-object.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:3825:21)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Object../node_modules/core-js/modules/es.array.iterator.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:4366:23)\n' +
    '    at __webpack_require__ (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:21:30)\n' +
    '    at Module.<anonymous> (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:6530:91)\n' +
    '    at Module../node_modules/webpack/buildin/global.js (C:\\Users\\USUARIO\\storefront\\node_modules\\css-loader\\dist\\cjs.js!C:\\Users\\USUARIO\\storefront\\node_modules\\postcss-loader\\src\\index.js??postcss!C:\\Users\\USUARIO\\storefront\\node_modules\\sass-loader\\dist\\cjs.js??ref--4-3!C:\\Users\\USUARIO\\storefront\\template\\scss\\styles.scss:6565:30)\n' +
    ' @ multi ./template/scss/styles.scss ./template/js/index.js storefront[0]'
]

**Comment by matheusgnreis** [comment]
lodash.clonedeep
lodash.merge
@ecomplus/widget-product-card

**Comment by matheusgnreis** [comment]
"export 'default' ... was not found in ...
above

**Comment by leomp12** [comment]
Até que enfim!
